### ISSUE TITLE
What about a global error handler?

### ISSUE THREAD

**Issue by IlSocio** [tierratelematics/ninjagoat#7]
Hi all, 
by any chance, does ninjagoat provide any helper method to install a Global Error Handler to handle all the uncaught errors at the application level?

Thanks,
Marco.

**Comment by lazyoft** [comment]
Hi,
There is very little added value in having the library handling errors at a global value out of the box. How should the framework respond to such events for a starter? It most likely will depend on the error, the severity and the overall business logic your application has to apply.
Ninjagoat is a framework that leverages the mvvm pattern along with an observable model, therefore its purpose is the one to provide a lean and straightforward way to manage state updates and everything that is related to making testable components whilst keeping the view engine decoupled.
Due to this we provide different modules that might help handling an error state. Such modules vary from basic dialogs to notification messages to wrapper around the console log which can be used along with some other library such as Winston in order to provide the most flexible possible approach. In your case I would recommend to just handle the window.onerror event handler and provide whatever business logic suits your application needs, even by leveraging existing ninjagoat components.

**Comment by IlSocio** [comment]
Thabk you for you support Fabrizio.


Basically, my question comes from my lack of knowledge of javascript and didn't know where start to implement a global error handler.




I'll try using the window.onerror as you suggested.




Marco.




Da: Fabrizio Chignoli


Inviato: lunedì 10 luglio, 11:56


Oggetto: Re: [tierratelematics/ninjagoat] What about a global error handler? (#7)


A: tierratelematics/ninjagoat


Cc: Marco Bellino, Author






Hi,


There is very little added value in having the library handling errors at a global value out of the box. How should the framework respond to such events for a starter? It most likely will depend on the error, the severity and the overall business logic your application has to apply.


Ninjagoat is a framework that leverages the mvvm pattern along with an observable model, therefore its purpose is the one to provide a lean and straightforward way to manage state updates and everything that is related to making testable components whilst keeping the view engine decoupled.


Due to this we provide different modules that might help handling an error state. Such modules vary from basic dialogs to notification messages to wrapper around the console log which can be used along with some other library such as Winston in order to provide the most flexible possible approach. In your case I would recommend to just handle the window.onerror event handler and provide whatever business logic suits your application needs, even by leveraging existing ninjagoat components.
